-- 食物参考库 (auto-generated by migrate.py)
-- static_foods: 常见食物标准数据 (from foods.csv)
-- custom_foods: 用户录入数据 (from custom_foods)

CREATE TABLE IF NOT EXISTS static_foods (
    id INTEGER PRIMARY KEY,
    category TEXT NOT NULL DEFAULT '',
    name TEXT NOT NULL,
    calories_per_100g REAL DEFAULT 0,
    carbs_per_100g REAL DEFAULT 0,
    protein_per_100g REAL DEFAULT 0,
    fat_per_100g REAL DEFAULT 0,
    fiber_per_100g REAL DEFAULT 0,
    note TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS custom_foods (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    barcode TEXT,
    brand TEXT DEFAULT '',
    serving_size_g REAL,
    serving_desc TEXT DEFAULT '',
    calories_per_100g REAL DEFAULT 0,
    carbs_per_100g REAL DEFAULT 0,
    protein_per_100g REAL DEFAULT 0,
    fat_per_100g REAL DEFAULT 0,
    fiber_per_100g REAL DEFAULT 0,
    added_date TEXT DEFAULT '',
    image_desc TEXT DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_custom_foods_barcode ON custom_foods(barcode);
CREATE INDEX IF NOT EXISTS idx_custom_foods_name ON custom_foods(name);

-- ─── static_foods ────────────────────────────────────────

INSERT INTO static_foods VALUES (1,'主食','米饭(熟)',116.0,25.9,2.6,0.3,0.4,'白米饭');
INSERT INTO static_foods VALUES (2,'主食','馒头',223.0,44.2,7.0,1.1,1.3,'小麦粉馒头');
INSERT INTO static_foods VALUES (3,'主食','面条(煮)',110.0,24.3,3.7,0.5,0.8,'挂面煮熟');
INSERT INTO static_foods VALUES (4,'主食','花卷',211.0,45.6,6.4,1.1,1.5,'');
INSERT INTO static_foods VALUES (5,'主食','油条',386.0,51.0,6.9,17.6,0.9,'');
INSERT INTO static_foods VALUES (6,'主食','小米粥(稀)',46.0,8.4,1.4,0.7,0.2,'水分约85%');
INSERT INTO static_foods VALUES (7,'主食','燕麦片(煮)',70.0,13.0,2.5,1.3,1.7,'无糖');
INSERT INTO static_foods VALUES (8,'主食','全麦面包',246.0,41.3,8.5,3.4,6.0,'');
INSERT INTO static_foods VALUES (9,'主食','白面包',265.0,49.4,8.4,3.4,2.4,'');
INSERT INTO static_foods VALUES (10,'主食','红薯(蒸)',86.0,20.1,1.6,0.1,3.0,'');
INSERT INTO static_foods VALUES (11,'主食','玉米(煮)',112.0,23.0,4.0,1.2,2.9,'');
INSERT INTO static_foods VALUES (12,'主食','土豆(煮)',76.0,17.5,2.0,0.1,1.6,'');
INSERT INTO static_foods VALUES (13,'主食','饺子(猪肉)',240.0,28.0,11.0,10.0,1.0,'约6个/100g');
INSERT INTO static_foods VALUES (14,'主食','馄饨',200.0,24.0,9.0,7.0,0.8,'');
INSERT INTO static_foods VALUES (15,'主食','包子(肉馅)',227.0,28.0,9.5,9.0,1.5,'');
INSERT INTO static_foods VALUES (16,'主食','粽子',180.0,32.0,4.5,4.0,1.2,'');
INSERT INTO static_foods VALUES (17,'主食','炒饭(蛋炒饭)',188.0,26.0,5.5,6.5,0.8,'');
INSERT INTO static_foods VALUES (18,'主食','炒面',158.0,23.0,5.0,5.0,0.8,'');
INSERT INTO static_foods VALUES (19,'肉类','鸡蛋(煮)',144.0,1.5,13.3,9.5,0.0,'约50g/个=72kcal');
INSERT INTO static_foods VALUES (20,'肉类','鸡蛋白',48.0,1.0,10.0,0.2,0.0,'');
INSERT INTO static_foods VALUES (21,'肉类','鸡蛋黄',328.0,3.0,15.2,28.2,0.0,'');
INSERT INTO static_foods VALUES (22,'肉类','煎鸡蛋',196.0,1.2,12.5,15.5,0.0,'含油');
INSERT INTO static_foods VALUES (23,'肉类','鸡胸肉(煮)',133.0,0.0,31.0,1.2,0.0,'');
INSERT INTO static_foods VALUES (24,'肉类','鸡腿肉(去皮)',119.0,0.0,24.0,2.6,0.0,'');
INSERT INTO static_foods VALUES (25,'肉类','鸡腿肉(带皮)',181.0,0.0,20.0,11.5,0.0,'');
INSERT INTO static_foods VALUES (26,'肉类','鸡翅',194.0,0.0,17.4,14.0,0.0,'');
INSERT INTO static_foods VALUES (27,'肉类','猪肉(瘦肉)',143.0,1.5,20.3,6.2,0.0,'');
INSERT INTO static_foods VALUES (28,'肉类','猪肉(五花肉)',349.0,0.0,13.0,33.0,0.0,'');
INSERT INTO static_foods VALUES (29,'肉类','猪排骨',264.0,0.0,18.3,20.4,0.0,'');
INSERT INTO static_foods VALUES (30,'肉类','猪肝',129.0,5.0,19.3,3.5,0.0,'');
INSERT INTO static_foods VALUES (31,'肉类','牛肉(瘦)',106.0,1.2,20.2,2.3,0.0,'');
INSERT INTO static_foods VALUES (32,'肉类','牛肉(肥牛)',250.0,0.0,17.0,20.0,0.0,'火锅肥牛');
INSERT INTO static_foods VALUES (33,'肉类','牛腩',153.0,0.8,18.0,8.0,0.0,'');
INSERT INTO static_foods VALUES (34,'肉类','羊肉(瘦)',118.0,0.0,20.5,3.9,0.0,'');
INSERT INTO static_foods VALUES (35,'肉类','羊肉(肥羊)',250.0,0.0,16.0,20.0,0.0,'火锅羊肉卷');
INSERT INTO static_foods VALUES (36,'肉类','鸭肉(带皮)',240.0,0.2,15.5,19.7,0.0,'');
INSERT INTO static_foods VALUES (37,'肉类','鸭肉(去皮)',140.0,0.2,20.0,6.5,0.0,'');
INSERT INTO static_foods VALUES (38,'肉类','火腿肠',212.0,7.0,14.0,15.0,0.0,'');
INSERT INTO static_foods VALUES (39,'肉类','培根',541.0,1.2,12.0,54.0,0.0,'');
INSERT INTO static_foods VALUES (40,'肉类','香肠',308.0,4.0,24.0,22.0,0.0,'');
INSERT INTO static_foods VALUES (41,'肉类','午餐肉',229.0,4.0,13.0,18.0,0.0,'');
INSERT INTO static_foods VALUES (42,'水产','鲈鱼(清蒸)',105.0,0.0,18.6,3.4,0.0,'');
INSERT INTO static_foods VALUES (43,'水产','三文鱼',208.0,0.0,20.4,13.6,0.0,'');
INSERT INTO static_foods VALUES (44,'水产','虾仁(煮)',60.0,0.0,14.0,0.8,0.0,'');
INSERT INTO static_foods VALUES (45,'水产','基围虾',93.0,0.0,20.0,1.0,0.0,'');
INSERT INTO static_foods VALUES (46,'水产','螃蟹(清蒸)',102.0,0.0,17.5,2.6,0.0,'');
INSERT INTO static_foods VALUES (47,'水产','蛤蜊',56.0,3.0,8.0,1.0,0.0,'');
INSERT INTO static_foods VALUES (48,'水产','带鱼(红烧)',185.0,1.5,17.7,11.0,0.0,'');
INSERT INTO static_foods VALUES (49,'水产','鱿鱼',75.0,1.0,16.0,0.9,0.0,'');
INSERT INTO static_foods VALUES (50,'豆制品','豆腐(嫩)',57.0,2.0,5.7,3.0,0.2,'');
INSERT INTO static_foods VALUES (51,'豆制品','豆腐(老)',81.0,2.0,8.1,4.2,0.5,'');
INSERT INTO static_foods VALUES (52,'豆制品','豆腐干',151.0,2.0,16.0,7.5,1.2,'');
INSERT INTO static_foods VALUES (53,'豆制品','豆皮',409.0,20.0,44.6,17.4,1.6,'干豆皮');
INSERT INTO static_foods VALUES (54,'豆制品','腐竹',459.0,16.0,44.6,21.7,1.0,'');
INSERT INTO static_foods VALUES (55,'豆制品','豆浆(无糖)',16.0,0.8,1.8,0.7,0.2,'');
INSERT INTO static_foods VALUES (56,'豆制品','豆浆(含糖)',33.0,5.0,1.8,0.7,0.2,'');
INSERT INTO static_foods VALUES (57,'蔬菜','番茄',18.0,3.3,0.9,0.2,1.2,'');
INSERT INTO static_foods VALUES (58,'蔬菜','黄瓜',15.0,2.5,0.8,0.2,0.5,'');
INSERT INTO static_foods VALUES (59,'蔬菜','生菜',13.0,1.5,1.3,0.3,0.7,'');
INSERT INTO static_foods VALUES (60,'蔬菜','菠菜',23.0,2.8,2.9,0.4,2.2,'');
INSERT INTO static_foods VALUES (61,'蔬菜','白菜',13.0,2.4,1.5,0.1,1.0,'');
INSERT INTO static_foods VALUES (62,'蔬菜','西兰花',34.0,4.0,3.7,0.6,2.6,'');
INSERT INTO static_foods VALUES (63,'蔬菜','花菜',24.0,3.2,2.1,0.4,1.8,'');
INSERT INTO static_foods VALUES (64,'蔬菜','青椒',22.0,4.0,1.0,0.2,1.4,'');
INSERT INTO static_foods VALUES (65,'蔬菜','胡萝卜(生)',39.0,8.8,1.0,0.2,2.8,'');
INSERT INTO static_foods VALUES (66,'蔬菜','白萝卜',18.0,3.6,0.9,0.1,1.0,'');
INSERT INTO static_foods VALUES (67,'蔬菜','洋葱',39.0,8.0,1.1,0.2,1.4,'');
INSERT INTO static_foods VALUES (68,'蔬菜','茄子',21.0,4.0,1.1,0.2,1.5,'');
INSERT INTO static_foods VALUES (69,'蔬菜','豆角',31.0,4.6,2.5,0.2,2.1,'');
INSERT INTO static_foods VALUES (70,'蔬菜','四季豆',28.0,4.2,2.0,0.2,2.7,'');
INSERT INTO static_foods VALUES (71,'蔬菜','莴笋',14.0,2.2,1.0,0.1,1.0,'');
INSERT INTO static_foods VALUES (72,'蔬菜','芹菜',14.0,1.8,0.8,0.1,1.2,'');
INSERT INTO static_foods VALUES (73,'蔬菜','韭菜',26.0,3.2,2.4,0.4,1.4,'');
INSERT INTO static_foods VALUES (74,'蔬菜','蒜薹',61.0,10.0,2.0,0.5,2.0,'');
INSERT INTO static_foods VALUES (75,'蔬菜','藕(炒)',78.0,16.4,1.9,0.2,1.4,'');
INSERT INTO static_foods VALUES (76,'蔬菜','山药',56.0,12.0,1.9,0.2,1.4,'');
INSERT INTO static_foods VALUES (77,'蔬菜','土豆丝(炒)',85.0,13.0,1.8,3.0,1.0,'含油');
INSERT INTO static_foods VALUES (78,'蔬菜','南瓜',22.0,4.5,0.7,0.1,1.1,'');
INSERT INTO static_foods VALUES (79,'蔬菜','冬瓜',11.0,2.0,0.3,0.2,0.7,'');
INSERT INTO static_foods VALUES (80,'蔬菜','丝瓜',18.0,2.5,1.0,0.2,0.6,'');
INSERT INTO static_foods VALUES (81,'蔬菜','苦瓜',19.0,3.0,1.0,0.1,1.5,'');
INSERT INTO static_foods VALUES (82,'蔬菜','玉米粒',112.0,22.8,4.0,1.2,2.9,'');
INSERT INTO static_foods VALUES (83,'蔬菜','香菇(鲜)',26.0,3.0,2.5,0.3,1.8,'');
INSERT INTO static_foods VALUES (84,'蔬菜','金针菇',26.0,3.0,2.2,0.4,1.5,'');
INSERT INTO static_foods VALUES (85,'蔬菜','杏鲍菇',31.0,4.0,2.1,0.3,1.7,'');
INSERT INTO static_foods VALUES (86,'蔬菜','木耳(水发)',26.0,3.5,1.7,0.2,2.5,'');
INSERT INTO static_foods VALUES (87,'蔬菜','海带(鲜)',15.0,1.5,1.2,0.1,1.5,'');
INSERT INTO static_foods VALUES (88,'蔬菜','紫菜(干)',207.0,22.0,28.6,1.1,27.3,'');
INSERT INTO static_foods VALUES (89,'蛋奶','鸡蛋',144.0,1.5,13.3,9.5,0.0,'已在肉类中');
INSERT INTO static_foods VALUES (90,'蛋奶','鸭蛋',180.0,1.0,12.6,13.0,0.0,'');
INSERT INTO static_foods VALUES (91,'蛋奶','鹌鹑蛋',160.0,1.5,12.8,11.1,0.0,'');
INSERT INTO static_foods VALUES (92,'蛋奶','牛奶(全脂)',61.0,4.8,3.2,3.3,0.0,'');
INSERT INTO static_foods VALUES (93,'蛋奶','牛奶(低脂)',43.0,5.0,3.5,1.0,0.0,'');
INSERT INTO static_foods VALUES (94,'蛋奶','牛奶(脱脂)',34.0,5.0,3.5,0.1,0.0,'');
INSERT INTO static_foods VALUES (95,'蛋奶','酸奶(原味)',72.0,9.3,2.5,2.5,0.0,'');
INSERT INTO static_foods VALUES (96,'蛋奶','酸奶(果味)',88.0,13.0,2.3,2.0,0.3,'');
INSERT INTO static_foods VALUES (97,'蛋奶','酸奶(无糖)',50.0,4.5,3.0,1.5,0.0,'');
INSERT INTO static_foods VALUES (98,'蛋奶','奶酪',328.0,1.0,25.0,25.0,0.0,'');
INSERT INTO static_foods VALUES (99,'水果','苹果',52.0,13.5,0.2,0.2,2.0,'中等约200g');
INSERT INTO static_foods VALUES (100,'水果','香蕉',91.0,22.0,1.4,0.2,1.8,'中等约120g');
INSERT INTO static_foods VALUES (101,'水果','橙子',47.0,11.0,0.8,0.2,1.7,'中等约200g');
INSERT INTO static_foods VALUES (102,'水果','草莓',32.0,7.0,0.7,0.2,1.4,'');
INSERT INTO static_foods VALUES (103,'水果','葡萄',43.0,10.0,0.5,0.2,0.8,'');
INSERT INTO static_foods VALUES (104,'水果','西瓜',31.0,7.0,0.6,0.1,0.3,'');
INSERT INTO static_foods VALUES (105,'水果','芒果',60.0,14.0,0.8,0.4,1.6,'');
INSERT INTO static_foods VALUES (106,'水果','蓝莓',57.0,14.0,0.7,0.3,2.4,'');
INSERT INTO static_foods VALUES (107,'水果','猕猴桃',61.0,14.0,0.8,0.6,2.1,'');
INSERT INTO static_foods VALUES (108,'水果','菠萝',44.0,10.0,0.5,0.2,1.3,'');
INSERT INTO static_foods VALUES (109,'水果','梨',50.0,13.0,0.4,0.2,3.0,'');
INSERT INTO static_foods VALUES (110,'水果','桃',48.0,11.0,0.7,0.2,1.3,'');
INSERT INTO static_foods VALUES (111,'水果','荔枝',66.0,16.0,0.8,0.4,0.5,'');
INSERT INTO static_foods VALUES (112,'水果','提子/葡萄干',299.0,72.0,3.0,0.5,3.5,'干果热量高');
INSERT INTO static_foods VALUES (113,'水果','红枣(干)',264.0,63.0,3.5,0.9,6.2,'');
INSERT INTO static_foods VALUES (114,'水果','核桃(干)',646.0,10.0,15.0,65.0,6.7,'坚果热量高');
INSERT INTO static_foods VALUES (115,'水果','杏仁',578.0,20.0,21.0,50.0,11.0,'');
INSERT INTO static_foods VALUES (116,'水果','腰果',553.0,30.0,18.0,44.0,3.3,'');
INSERT INTO static_foods VALUES (117,'水果','开心果',560.0,28.0,20.0,45.0,10.0,'');
INSERT INTO static_foods VALUES (118,'水果','花生(炒)',585.0,17.0,24.0,49.0,6.3,'');
INSERT INTO static_foods VALUES (119,'水果','瓜子(炒)',582.0,13.0,23.0,49.0,7.5,'');
INSERT INTO static_foods VALUES (120,'水果','牛油果',160.0,9.0,2.0,15.0,6.7,'');
INSERT INTO static_foods VALUES (121,'饮品','可口可乐',43.0,10.6,0.0,0.0,0.0,'');
INSERT INTO static_foods VALUES (122,'饮品','雪碧',41.0,10.2,0.0,0.0,0.0,'');
INSERT INTO static_foods VALUES (123,'饮品','橙汁(纯)',45.0,10.4,0.7,0.2,0.2,'');
INSERT INTO static_foods VALUES (124,'饮品','苹果汁',46.0,11.3,0.1,0.1,0.2,'');
INSERT INTO static_foods VALUES (125,'饮品','啤酒',43.0,3.5,0.5,0.0,0.0,'');
INSERT INTO static_foods VALUES (126,'饮品','红酒',85.0,2.6,0.1,0.0,0.0,'');
INSERT INTO static_foods VALUES (127,'饮品','白酒',298.0,1.8,0.0,0.0,0.0,'按100ml计(通常小杯50ml)');
INSERT INTO static_foods VALUES (128,'饮品','珍珠奶茶',75.0,12.0,0.5,2.5,0.0,'中杯约450ml≈338kcal');
INSERT INTO static_foods VALUES (129,'饮品','拿铁咖啡',34.0,3.0,1.8,1.5,0.0,'中杯约350ml≈119kcal');
INSERT INTO static_foods VALUES (130,'饮品','美式咖啡',2.0,0.0,0.1,0.0,0.0,'几乎无热量');
INSERT INTO static_foods VALUES (131,'饮品','速溶咖啡(3合1)',84.0,14.0,1.5,2.5,0.0,'每包约15g');
INSERT INTO static_foods VALUES (132,'油脂酱料','植物油',899.0,0.0,0.0,99.9,0.0,'每勺约10g≈90kcal');
INSERT INTO static_foods VALUES (133,'油脂酱料','猪油',897.0,0.0,0.0,99.6,0.0,'');
INSERT INTO static_foods VALUES (134,'油脂酱料','黄油',717.0,0.0,0.8,81.0,0.0,'');
INSERT INTO static_foods VALUES (135,'油脂酱料','沙拉酱(蛋黄)',680.0,2.0,1.0,75.0,0.0,'');
INSERT INTO static_foods VALUES (136,'油脂酱料','沙拉酱(油醋汁)',290.0,3.0,0.0,30.0,0.0,'');
INSERT INTO static_foods VALUES (137,'油脂酱料','番茄酱',80.0,16.0,1.5,0.2,1.5,'');
INSERT INTO static_foods VALUES (138,'油脂酱料','辣椒油',900.0,0.0,0.0,99.9,0.0,'');
INSERT INTO static_foods VALUES (139,'油脂酱料','芝麻酱',616.0,14.0,19.2,53.0,5.0,'');
INSERT INTO static_foods VALUES (140,'油脂酱料','花生酱',588.0,20.0,25.0,50.0,5.0,'');
INSERT INTO static_foods VALUES (141,'油脂酱料','蚝油',89.0,10.0,2.0,0.5,0.0,'');
INSERT INTO static_foods VALUES (142,'油脂酱料','生抽',32.0,4.0,5.0,0.0,0.0,'');
INSERT INTO static_foods VALUES (143,'油脂酱料','老抽',42.0,6.0,6.0,0.0,0.0,'');
INSERT INTO static_foods VALUES (144,'油脂酱料','醋',18.0,2.0,0.5,0.0,0.0,'');
INSERT INTO static_foods VALUES (145,'油脂酱料','白糖',400.0,100.0,0.0,0.0,0.0,'每勺约5g≈20kcal');
INSERT INTO static_foods VALUES (146,'油脂酱料','蜂蜜',321.0,80.3,0.4,0.0,0.2,'');
INSERT INTO static_foods VALUES (147,'油脂酱料','果酱',250.0,60.0,0.5,0.1,1.0,'');
INSERT INTO static_foods VALUES (148,'快餐','汉堡(牛肉)',265.0,28.0,13.0,12.0,1.5,'约150g');
INSERT INTO static_foods VALUES (149,'快餐','汉堡(鸡肉)',250.0,28.0,14.0,10.0,1.5,'');
INSERT INTO static_foods VALUES (150,'快餐','薯条(中份)',312.0,41.0,3.4,15.0,3.8,'约117g');
INSERT INTO static_foods VALUES (151,'快餐','炸鸡翅',290.0,12.0,18.0,20.0,0.5,'4-5只');
INSERT INTO static_foods VALUES (152,'快餐','披萨(肉)',266.0,28.0,11.4,11.8,1.6,'一片约150g');
INSERT INTO static_foods VALUES (153,'快餐','三明治',233.0,28.0,12.0,9.0,1.8,'');
INSERT INTO static_foods VALUES (154,'快餐','热狗',290.0,24.0,10.0,17.0,1.0,'');
INSERT INTO static_foods VALUES (155,'快餐','寿司(每贯)',40.0,7.0,1.5,0.3,0.2,'约15-20g/贯');
INSERT INTO static_foods VALUES (156,'快餐','方便面(泡)',440.0,58.0,9.0,18.0,1.5,'一份含汤');
INSERT INTO static_foods VALUES (157,'零食','薯片',536.0,50.0,5.0,35.0,4.0,'');
INSERT INTO static_foods VALUES (158,'零食','饼干',433.0,65.0,7.0,16.0,2.0,'');
INSERT INTO static_foods VALUES (159,'零食','巧克力',546.0,57.0,5.0,31.0,3.0,'');
INSERT INTO static_foods VALUES (160,'零食','冰淇淋',180.0,24.0,3.5,7.5,0.0,'');
INSERT INTO static_foods VALUES (161,'零食','蛋糕(奶油)',349.0,45.0,5.0,16.0,0.5,'');
INSERT INTO static_foods VALUES (162,'零食','蛋黄派',430.0,48.0,5.0,24.0,1.0,'');
INSERT INTO static_foods VALUES (163,'零食','沙琪玛',506.0,55.0,6.0,29.0,1.0,'');
INSERT INTO static_foods VALUES (164,'零食','牛肉干',550.0,1.0,45.0,40.0,0.0,'');
INSERT INTO static_foods VALUES (165,'零食','猪肉脯',378.0,10.0,35.0,24.0,0.0,'');
INSERT INTO static_foods VALUES (166,'零食','鱿鱼丝',315.0,3.0,60.0,4.5,0.0,'');
INSERT INTO static_foods VALUES (167,'中餐热菜','番茄炒蛋',85.0,4.0,4.5,5.5,0.8,'含油');
INSERT INTO static_foods VALUES (168,'中餐热菜','宫保鸡丁',165.0,7.0,15.0,9.5,1.5,'含油+花生');
INSERT INTO static_foods VALUES (169,'中餐热菜','鱼香肉丝',145.0,5.0,10.0,9.0,1.0,'');
INSERT INTO static_foods VALUES (170,'中餐热菜','糖醋里脊',220.0,18.0,12.0,12.0,0.5,'');
INSERT INTO static_foods VALUES (171,'中餐热菜','红烧肉',305.0,8.0,15.0,25.0,0.5,'');
INSERT INTO static_foods VALUES (172,'中餐热菜','回锅肉',265.0,5.0,14.0,22.0,1.0,'');
INSERT INTO static_foods VALUES (173,'中餐热菜','麻婆豆腐',110.0,5.0,8.0,7.0,1.2,'');
INSERT INTO static_foods VALUES (174,'中餐热菜','地三鲜',120.0,10.0,2.0,8.0,2.0,'含油');
INSERT INTO static_foods VALUES (175,'中餐热菜','干煸四季豆',130.0,6.0,3.0,10.0,3.0,'含油多');
INSERT INTO static_foods VALUES (176,'中餐热菜','蒜蓉西兰花',55.0,4.0,3.5,2.5,2.5,'');
INSERT INTO static_foods VALUES (177,'中餐热菜','酸辣土豆丝',90.0,12.0,1.5,4.0,1.0,'');
INSERT INTO static_foods VALUES (178,'中餐热菜','红烧茄子',120.0,10.0,1.5,8.0,1.5,'茄子吸油');
INSERT INTO static_foods VALUES (179,'中餐热菜','木须肉',120.0,3.0,10.0,7.0,1.0,'');
INSERT INTO static_foods VALUES (180,'中餐热菜','可乐鸡翅',180.0,10.0,16.0,10.0,0.3,'');
INSERT INTO static_foods VALUES (181,'中餐热菜','水煮肉片',220.0,3.0,18.0,16.0,1.0,'油多');
INSERT INTO static_foods VALUES (182,'中餐热菜','清蒸鲈鱼',95.0,0.5,18.0,2.5,0.0,'');
INSERT INTO static_foods VALUES (183,'中餐热菜','酸菜鱼',80.0,2.0,12.0,3.0,0.5,'汤不算');
INSERT INTO static_foods VALUES (184,'中餐热菜','炒青菜',35.0,3.0,2.0,1.5,2.0,'清炒含少量油');
INSERT INTO static_foods VALUES (185,'中餐热菜','白灼菜心',25.0,2.5,2.0,0.5,1.8,'');
INSERT INTO static_foods VALUES (186,'中餐热菜','蚝油生菜',40.0,3.5,1.5,2.0,1.0,'');
INSERT INTO static_foods VALUES (187,'中餐热菜','上汤娃娃菜',40.0,3.0,2.0,2.0,1.5,'');
INSERT INTO static_foods VALUES (188,'中餐汤羹','紫菜蛋花汤',25.0,1.5,2.0,1.2,0.3,'');
INSERT INTO static_foods VALUES (189,'中餐汤羹','番茄蛋汤',30.0,2.0,1.5,1.5,0.3,'');
INSERT INTO static_foods VALUES (190,'中餐汤羹','排骨汤',55.0,1.0,3.0,4.5,0.0,'');
INSERT INTO static_foods VALUES (191,'中餐汤羹','鸡汤',35.0,0.5,3.0,2.5,0.0,'去油');
INSERT INTO static_foods VALUES (192,'中餐汤羹','鱼汤',30.0,0.3,3.5,2.0,0.0,'');
INSERT INTO static_foods VALUES (193,'中餐汤羹','酸辣汤',35.0,3.0,2.0,1.5,0.5,'');
INSERT INTO static_foods VALUES (194,'中餐汤羹','味噌汤',25.0,1.5,2.0,0.5,0.5,'');
INSERT INTO static_foods VALUES (195,'中餐汤羹','火锅麻辣汤底',120.0,2.0,2.0,12.0,0.5,'汤底不算食材');
INSERT INTO static_foods VALUES (196,'中餐汤羹','火锅清汤底',5.0,0.5,0.3,0.2,0.0,'');
INSERT INTO static_foods VALUES (197,'蛋奶','无油煎蛋',100.0,1.0,12.0,6.0,0.0,'约50g/个，无油煎，脂肪仅蛋黄自带');

-- ─── custom_foods ────────────────────────────────────────

INSERT INTO custom_foods VALUES (1,'鱼片青菜粥','','',NULL,'',0,0,0,0,0,'2026-05-14 19:37:48','');
INSERT INTO custom_foods VALUES (2,'韭菜鸡蛋包子','','',NULL,'',0,0,0,0,0,'2026-05-14 19:37:48','');
INSERT INTO custom_foods VALUES (3,'朴诚风味发酵乳(含LGG)','6970618570773','朴诚乳业',100.0,'每100g',94.0,12.5,3.0,3.5,0,'2026-05-15 06:23:45','');
INSERT INTO custom_foods VALUES (4,'无油煎蛋','','',NULL,'',0,0,0,0,0,'2026-05-16 06:48:35','');
INSERT INTO custom_foods VALUES (5,'奥乐齐低脂日式火腿片','6971906850980','奥乐齐(ALDI)',50.0,'1/3包',110.0,6.5,18.2,1.1,0,'2026-05-17 06:56:16','');
INSERT INTO custom_foods VALUES (6,'骨元素(钙蛋白粉)','','骨元素',15.0,'1份',373.0,31.3,50.0,4.7,0,'2026-05-17 06:56:24','');
INSERT INTO custom_foods VALUES (7,'莱牧高蛋白零脂脱乳糖酸奶','','莱牧乳业',100.0,'1杯',60.0,4.5,10.2,0,0,'2026-05-17 06:56:24','');
INSERT INTO custom_foods VALUES (8,'卡士佐餐酪乳(风味发酵乳)','','Classy Kiss',100.0,'1杯',93.0,12.0,2.8,3.7,0,'2026-05-18 18:07:03','');
INSERT INTO custom_foods VALUES (9,'瑞士莲软心黑巧克力(悠享装)','','Lindt',200.0,'1包',614.0,42.4,4.0,48.1,0,'2026-05-18 18:43:09','');
INSERT INTO custom_foods VALUES (10,'桃李高纤维全麦面包','6975713791368','桃李',60.0,'2片',277.0,42.0,10.6,5.7,6.5,'2026-05-19 07:40:38','');
INSERT INTO custom_foods VALUES (11,'虾仁鸡胸肉饼','','',200.0,'200g(约2块)',106.1,1.4,20.8,2.0,0.5,'2026-05-19 07:40:47','');
