#!/usr/bin/env python3
"""一次性迁移脚本：拆分 calories.db → foods.db + records.db，并生成 foods.sql"""

import csv
import os
import sqlite3
import sys

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPTS_DIR)
DATA_DIR = os.path.expanduser("~/.openclaw/data/calorie-tracker")

OLD_DB = os.path.join(DATA_DIR, "calories.db")
NEW_RECORDS_DB = os.path.join(DATA_DIR, "records.db")
FOODS_DB = os.path.join(PROJECT_DIR, "data", "foods.db")
FOODS_SQL = os.path.join(PROJECT_DIR, "data", "foods.sql")
FOODS_CSV = os.path.join(PROJECT_DIR, "data", "foods.csv")

# ─── Schema ──────────────────────────────────────────────────

FOODS_SCHEMA = """
CREATE TABLE IF NOT EXISTS static_foods (
    id INTEGER PRIMARY KEY,
    category TEXT NOT NULL DEFAULT '',
    name TEXT NOT NULL,
    calories_per_100g REAL DEFAULT 0,
    carbs_per_100g REAL DEFAULT 0,
    protein_per_100g REAL DEFAULT 0,
    fat_per_100g REAL DEFAULT 0,
    fiber_per_100g REAL DEFAULT 0,
    note TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS custom_foods (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    barcode TEXT,
    brand TEXT DEFAULT '',
    serving_size_g REAL,
    serving_desc TEXT DEFAULT '',
    calories_per_100g REAL DEFAULT 0,
    carbs_per_100g REAL DEFAULT 0,
    protein_per_100g REAL DEFAULT 0,
    fat_per_100g REAL DEFAULT 0,
    fiber_per_100g REAL DEFAULT 0,
    added_date TEXT DEFAULT '',
    image_desc TEXT DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_custom_foods_barcode ON custom_foods(barcode);
CREATE INDEX IF NOT EXISTS idx_custom_foods_name ON custom_foods(name);
"""

RECORDS_SCHEMA = """
CREATE TABLE IF NOT EXISTS meals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    meal_time TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    meal_type TEXT DEFAULT '',
    foods_json TEXT NOT NULL,
    total_calories REAL DEFAULT 0,
    total_carbs REAL DEFAULT 0,
    total_protein REAL DEFAULT 0,
    total_fat REAL DEFAULT 0,
    total_fiber REAL DEFAULT 0,
    image_desc TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS goals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    calorie_goal INTEGER NOT NULL DEFAULT 2000,
    set_date TEXT NOT NULL DEFAULT (datetime('now', 'localtime'))
);

CREATE TABLE IF NOT EXISTS macro_goals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    calorie INTEGER DEFAULT 2000,
    protein_g REAL,
    carbs_g REAL,
    fat_g REAL,
    fiber_g REAL,
    set_date TEXT DEFAULT (datetime('now', 'localtime'))
);

CREATE TABLE IF NOT EXISTS weight_records (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    weight REAL NOT NULL,
    recorded_at TEXT DEFAULT (datetime('now', 'localtime')),
    note TEXT DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_weight_date ON weight_records(recorded_at);
"""


def load_csv(path):
    """读取 foods.csv 返回行列表"""
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for i, row in enumerate(reader, 1):
            rows.append({
                "id": i,
                "category": row.get("分类", ""),
                "name": row.get("食物名称", ""),
                "calories_per_100g": float(row.get("每100g热量(kcal)", 0) or 0),
                "carbs_per_100g": float(row.get("碳水(g)", 0) or 0),
                "protein_per_100g": float(row.get("蛋白质(g)", 0) or 0),
                "fat_per_100g": float(row.get("脂肪(g)", 0) or 0),
                "fiber_per_100g": float(row.get("膳食纤维(g)", 0) or 0),
                "note": row.get("备注", ""),
            })
    return rows


def migrate_custom_foods(old_conn):
    """从旧库读取 custom_foods"""
    rows = old_conn.execute("SELECT * FROM custom_foods ORDER BY id").fetchall()
    return [dict(r) for r in rows]


def migrate_records(old_conn, new_conn):
    """迁移 meals, goals, macro_goals, weight_records"""
    tables = ["meals", "goals", "macro_goals", "weight_records"]
    for table in tables:
        rows = old_conn.execute(f"SELECT * FROM {table}").fetchall()
        if not rows:
            continue
        cols = rows[0].keys()
        placeholders = ", ".join(["?"] * len(cols))
        col_names = ", ".join(cols)
        for row in rows:
            new_conn.execute(
                f"INSERT OR IGNORE INTO {table} ({col_names}) VALUES ({placeholders})",
                tuple(row),
            )
        print(f"  ✅ {table}: {len(rows)} rows")


def export_foods_sql(foods_db_path, sql_path, csv_rows, custom_rows):
    """将食物数据导出为纯文本 SQL"""
    with open(sql_path, "w", encoding="utf-8") as f:
        f.write("-- 食物参考库 (auto-generated by migrate.py)\n")
        f.write("-- static_foods: 常见食物标准数据 (from foods.csv)\n")
        f.write("-- custom_foods: 用户录入数据 (from custom_foods)\n\n")
        f.write(FOODS_SCHEMA.strip())
        f.write("\n\n")

        # static_foods INSERT
        f.write("-- ─── static_foods ────────────────────────────────────────\n\n")
        for r in csv_rows:
            f.write(
                f"INSERT INTO static_foods VALUES ({r['id']},"
                f"'{r['category']}','{r['name']}',"
                f"{r['calories_per_100g']},{r['carbs_per_100g']},"
                f"{r['protein_per_100g']},{r['fat_per_100g']},"
                f"{r['fiber_per_100g']},'{r['note']}');\n"
            )

        f.write("\n-- ─── custom_foods ────────────────────────────────────────\n\n")
        for r in custom_rows:
            barcode = r.get("barcode") or ""
            brand = r.get("brand") or ""
            serving_size = r.get("serving_size_g") or "NULL"
            serving_desc = r.get("serving_desc") or ""
            added_date = r.get("added_date") or ""
            image_desc = r.get("image_desc") or ""
            # Escape single quotes
            name = r["name"].replace("'", "''")
            barcode = barcode.replace("'", "''") if barcode else ""
            brand = brand.replace("'", "''")
            serving_desc = serving_desc.replace("'", "''")
            added_date = added_date.replace("'", "''")
            image_desc = image_desc.replace("'", "''")

            f.write(
                f"INSERT INTO custom_foods VALUES ({r['id']},"
                f"'{name}','{barcode}','{brand}',"
                f"{serving_size},'{serving_desc}',"
                f"{r.get('calories_per_100g', 0) or 0},"
                f"{r.get('carbs_per_100g', 0) or 0},"
                f"{r.get('protein_per_100g', 0) or 0},"
                f"{r.get('fat_per_100g', 0) or 0},"
                f"{r.get('fiber_per_100g', 0) or 0},"
                f"'{added_date}','{image_desc}');\n"
            )

    print(f"  ✅ 导出 SQL: {sql_path} ({os.path.getsize(sql_path)} bytes)")


def main():
    # 检查旧库存在
    if not os.path.exists(OLD_DB):
        print(f"❌ 旧数据库不存在: {OLD_DB}")
        sys.exit(1)

    print("🚀 开始迁移...\n")

    # 1. 读取数据源
    print("📥 读取数据源...")
    csv_rows = load_csv(FOODS_CSV)
    print(f"  foods.csv: {len(csv_rows)} 条静态食物")

    old_conn = sqlite3.connect(OLD_DB)
    old_conn.row_factory = sqlite3.Row
    custom_rows = migrate_custom_foods(old_conn)
    print(f"  custom_foods: {len(custom_rows)} 条自定义食物")

    # 2. 构建 foods.db
    print("\n📦 构建 foods.db...")
    if os.path.exists(FOODS_DB):
        os.remove(FOODS_DB)
    foods_conn = sqlite3.connect(FOODS_DB)
    foods_conn.executescript(FOODS_SCHEMA)
    for r in csv_rows:
        foods_conn.execute(
            "INSERT INTO static_foods VALUES (?,?,?,?,?,?,?,?,?)",
            (r["id"], r["category"], r["name"], r["calories_per_100g"],
             r["carbs_per_100g"], r["protein_per_100g"], r["fat_per_100g"],
             r["fiber_per_100g"], r["note"]),
        )
    for r in custom_rows:
        foods_conn.execute(
            "INSERT INTO custom_foods VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (r["id"], r["name"], r.get("barcode"), r.get("brand", ""),
             r.get("serving_size_g"), r.get("serving_desc", ""),
             r.get("calories_per_100g", 0) or 0,
             r.get("carbs_per_100g", 0) or 0,
             r.get("protein_per_100g", 0) or 0,
             r.get("fat_per_100g", 0) or 0,
             r.get("fiber_per_100g", 0) or 0,
             r.get("added_date", ""), r.get("image_desc", "")),
        )
    foods_conn.commit()
    print(f"  ✅ foods.db 已创建: {FOODS_DB}")

    # 3. 构建 records.db
    print("\n📦 构建 records.db...")
    if os.path.exists(NEW_RECORDS_DB):
        os.remove(NEW_RECORDS_DB)
    rec_conn = sqlite3.connect(NEW_RECORDS_DB)
    rec_conn.executescript(RECORDS_SCHEMA)
    migrate_records(old_conn, rec_conn)
    rec_conn.commit()
    print(f"  ✅ records.db 已创建: {NEW_RECORDS_DB}")

    # 4. 导出 foods.sql
    print("\n📝 导出 foods.sql...")
    export_foods_sql(FOODS_DB, FOODS_SQL, csv_rows, custom_rows)

    # 关闭连接
    old_conn.close()
    foods_conn.close()
    rec_conn.close()

    print("\n🎉 迁移完成!")
    print(f"   foods.db:  {FOODS_DB}")
    print(f"   foods.sql: {FOODS_SQL}")
    print(f"   records.db: {NEW_RECORDS_DB}")
    print(f"\n⚠️  旧库保留未删: {OLD_DB}")
    print(f"   确认无误后可手动删除: rm {OLD_DB}")


if __name__ == "__main__":
    main()
